version: "3"

services:
    lunchbot:
        build: .
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - ./lunchbot.cfg:/data/lunchbot.cfg
            - ./data.txt:/data/data.txt
